### ISSUE TITLE
Expand GitLab variables

### ISSUE THREAD

**Issue by duckbrain** [duckbrain/beluga#8]
Due to some limitations in GitLab CI (which this project aims to overcome), sometimes variables have values expanded, but in some circumstances they are not.

eg:

```yaml
variables:
  FOO: http://$BAR

job1:
  environment:
    url: $FOO # Will expose `http://$BAR` in the $CI_ENVIRONMENT_URL 
```

We should implement a GitLab compatible variable expansion and use it on a case-by-case basis in the GitLab parser to expand variables in the values of the provided variables.

```go
var gitlabVariable = regexp.MustParse(...) // variable name by subquery.
func (env Environment) Expand(r regexp.RegExp, s string) string
```
